#!/usr/bin/env python3
"""
Dump reference outputs from the Python mission worker.

Imports the model directly rather than going through FastAPI, so the
reference can be regenerated with nothing but the standard library — no
server, no dependencies, no network.

    python3 tools/dump_reference.py [out.json]

The result feeds `tools/parity-check.mjs`, which asserts the browser engine
reproduces every one of these numbers.
"""
import datetime as dt
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "worker"))

from app import comms, geo, mission, power, science    # noqa: E402
from app.config import AOI, TIMELINE_SEGMENTS          # noqa: E402
from app.desalination import schedule                  # noqa: E402
from app.impact import impact                          # noqa: E402

# Chosen to straddle every boundary the new timeline has: the three mode
# transitions, and the acquisition and loss of signal at all three ground
# stations. A parity harness that only samples the middle of segments will
# not catch an off-by-one in a boundary test.
SLIDERS = [0, 0.05, 0.10, 0.15, 0.1799, 0.18, 0.25, 0.34, 0.40, 0.4452,
           0.50, 0.5569, 0.557, 0.60, 0.70, 0.75, 0.8615, 0.8616, 0.90,
           0.96, 0.999]

# The desalination schedule depends on the real Gulf-time hour, so it is
# dumped at a pinned hour and the JS side is asked for the same one.
PINNED_HOUR = 9

GULF = dt.timezone(dt.timedelta(hours=4))


def field(slider, nx, ny):
    t = mission.slider_to_loop_t(slider)
    w, s, e, n = AOI["bbox"]
    values, peak = [], 0.0
    for j in range(ny):
        lat = s + (n - s) * (j / (ny - 1))
        for i in range(nx):
            lon = w + (e - w) * (i / (nx - 1))
            v = science.chlorophyll_mg_m3(lat, lon, t)
            peak = max(peak, v)
            values.append(round(v, 3))
    return {"bbox": AOI["bbox"], "nx": nx, "ny": ny, "max": round(peak, 3),
            "values": values}


def warp_samples(n=64):
    """The warp curve itself — the piece most at risk of silent drift."""
    rows = []
    for k in range(n + 1):
        lt = mission.LOOP_DURATION_S * k / n
        # Full precision on the input: the JS side recomputes from this
        # number, so rounding it here would feed the two implementations
        # different arguments and report the difference as a mismatch.
        rows.append({
            "loop_t_s": lt,
            "orbit_s": round(geo.orbit_seconds(lt), 6),
            "compression": round(geo.time_compression(lt), 6),
        })
    return rows


def closure():
    """The whole point of the redesign: start and end must be the same place."""
    a = geo.subsatellite_point(0.0)
    b = geo.subsatellite_point(mission.LOOP_DURATION_S)
    return {
        "start": {"lat": round(a["lat"], 9), "lon": round(a["lon"], 9)},
        "end": {"lat": round(b["lat"], 9), "lon": round(b["lon"], 9)},
        "delta_deg": round(max(abs(a["lat"] - b["lat"]),
                               abs(a["lon"] - b["lon"])), 12),
    }


def main():
    out_path = (sys.argv[1] if len(sys.argv) > 1
                else os.path.join(ROOT, "tools", "reference.json"))

    t_active = mission.slider_to_loop_t(0.70)
    p_active = geo.subsatellite_point(t_active)
    sched = schedule("ACTIVE", t_active,
                     dt.datetime(2026, 9, 18, PINNED_HOUR, 0, tzinfo=GULF))

    ref = {
        "_note": "Generated by tools/dump_reference.py from the Python worker. "
                 "Regenerate after any change to worker/app/.",
        "sliders": SLIDERS,
        "pinned_hour": PINNED_HOUR,
        "segments": TIMELINE_SEGMENTS,
        "closure": closure(),
        "warp": warp_samples(),
        "derived": {
            "orbital_velocity_kms": round(geo.orbital_velocity_kms(), 4),
            "ground_speed_kms": round(geo.ground_speed_kms(), 4),
            "array_peak_w": round(power.PEAK_ARRAY_W, 2),
            "soc_envelope": power.soc_bounds(),
            "compression_bounds": geo.compression_bounds(),
            "network_contact_s": round(comms.network_contact_s(), 0),
        },
        "contacts": [
            {"station_id": e["station"]["id"], "windows": e["windows"]}
            for e in comms.all_passes()
        ],
        "field": field(0.70, 24, 12),
        "states": {
            str(s): mission.snapshot(s, include_schedule=False)
            for s in SLIDERS
        },
        "spectrum": science.spectrum(p_active["lat"], p_active["lon"],
                                     phase=t_active, bands=96),
        "desalination": sched,
        "impact": impact(sched),
    }

    with open(out_path, "w") as fh:
        json.dump(ref, fh, indent=1, sort_keys=True)

    size = os.path.getsize(out_path) / 1024
    print(f"wrote {out_path} ({size:.0f} KB)")
    print(f"  {len(SLIDERS)} full states, "
          f"{len(ref['spectrum']['bands'])} spectral bands, "
          f"{len(ref['field']['values'])} field cells, "
          f"{len(ref['warp'])} warp samples, "
          f"{sum(len(c['windows']) for c in ref['contacts'])} contact windows, "
          f"{len(ref['desalination']['plants'])} plants")
    print(f"  loop closure delta: {ref['closure']['delta_deg']:.2e} deg")


if __name__ == "__main__":
    main()
